=== JoelVegaC/TFG-Restaurante/Restaurante-DAM/Lenguaje de Marcas/restaurante.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="restaurante">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string"/>
                <xs:element name="direccion" type="xs:string"/>
                <xs:element name="carta">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="categoria" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="plato" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nombre" type="xs:string"/>
                                                    <xs:element name="descripcion" type="xs:string"/>
                                                    <xs:element name="precio" type="xs:decimal"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="tipo" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== JoelVegaC/TFG-Restaurante/Restaurante-DAM/Lenguaje de Marcas/restaurante.xml
<?xml version="1.0" encoding="UTF-8"?>
<restaurante xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="restaurante.xsd">

    <nombre>Vacio Espiritual </nombre>
    <direccion>Shibuya Street 35, Tokyo</direccion>

    <carta>

        <categoria tipo="Entrantes">
            <plato>
                <nombre>Croquetas Infinitas</nombre>
                <descripcion>Crujientes y cremosas</descripcion>
                <precio>6.50</precio>
            </plato>

            <plato>
                <nombre>Patata Mechada</nombre>
                <descripcion>Patatas con carne mechada</descripcion>
                <precio>7.00</precio>
            </plato>
        </categoria>

        <categoria tipo="Primeros">
            <plato>
                <nombre>Makis con salsa de Yuta</nombre>
                <descripcion>Makis con salsa especial</descripcion>
                <precio>12.00</precio>
            </plato>
        </categoria>

        <categoria tipo="Bebidas">
            <plato>
                <nombre>Té Zen'in</nombre>
                <descripcion>Té frío artesanal</descripcion>
                <precio>3.50</precio>
            </plato>
        </categoria>

    </carta>

</restaurante>
